### ISSUE TITLE
Chrome not closing?

### ISSUE THREAD

**Issue by 7ammer** [LucianoGanga/simple-headless-chrome#18] opened 2017-06-29 13:05 UTC
Brilliant package! It simplifies things greatly :)

However after running any script with this package chrome refuses to close. Below is an example script I'm currently working on that produces this issue. Am I doing something wrong?

Chrome Version: `59.0.3071.109`

```javascript
const fs = require('fs')
const HeadlessChrome = require('simple-headless-chrome')

const browser = new HeadlessChrome({
	headless: true
})

async function printToPDF(url, params = {}) {
	await browser.init()
	await browser.goTo(url)

	var pdf = await browser.printToPDF(params)
	fs.writeFile('./output.pdf', pdf, 'base64',()=> {})

	await browser.close()
        // process.exit(0) // closes node process but not chrome
}

printToPDF('http://google.com')

```

**Comment by wuvluv** [comment] 2017-06-29 19:37
Pass true

`await browser.close(true)`

**Comment by 7ammer** [comment] 2017-06-29 20:38
All is working well now. Cheers @wuvluv! :)

**Comment by JarrodCTaylor** [comment] 2017-06-29 21:28
I'm seeing the same behavior where chrome does not close. Passing `true` to close seemingly makes no difference.  

Chrome version: 59.0.3071.115
Same script as posted by 7ammer

**Comment by 7ammer** [comment] 2017-06-30 10:45
Hmm thats odd. Just an fyi I I'm using macOs.

**Comment by LucianoGanga** [comment] 2017-06-30 13:49
@JarrodCTaylor, what OS are you using?

**Comment by JarrodCTaylor** [comment] 2017-06-30 14:02
I am on macOS Sierra 10.12.5

Upon closer inspection the browser is closing. It hangs because the process never closes without an explicit `process.exit`. Is that expected behavior?

**Comment by 7ammer** [comment] 2017-06-30 14:39
@JarrodCTaylor, I believe `process.exit` is not supposed to be used to end a task. In my case above I tried using it in the hope that ending the node session would also end chrome. However this was not the case hence I commented it out.

**Comment by LucianoGanga** [comment] 2017-07-16 14:08
@JarrodCTaylor, do you still have the issue? 

Cheers!
Luciano

**Comment by JarrodCTaylor** [comment] 2017-07-18 19:48
This can be closed. Thanks

**Closed** 2017-07-25 04:37 UTC
